function Carrusel() {
    return (
        <div className="w-full max-w-[950px] mx-auto overflow-x-hidden bg-white md:rounded-xl shadow-md md:px-4">
            <div className="relative flex overflow-x-hidden">
                <div className="flex whitespace-nowrap items-center animate-loop-scroll w-max">
                    <img
                        loading="lazy"
                        src="/logos/logo1.webp"
                        alt=""
                        width="150"
                        className="inline-block"
                    />
                    <img
                        loading="lazy"
                        src="/logos/logo2.webp"
                        alt=""
                        width="150"
                        className="inline-block"
                    />
                    <img
                        loading="lazy"
                        src="/logos/logo3.webp"
                        alt=""
                        width="150"
                        className="inline-block"
                    />
                    <img
                        loading="lazy"
                        src="/logos/logo4.webp"
                        alt=""
                        width="150"
                        className="inline-block"
                    />
                    <img
                        loading="lazy"
                        src="/logos/logo5.webp"
                        alt=""
                        width="150"
                        className="inline-block"
                    />
                    <img
                        loading="lazy"
                        src="/logos/logo6.webp"
                        alt=""
                        width="150"
                        className="inline-block"
                    />
                    <img
                        loading="lazy"
                        src="/logos/logo1.webp"
                        alt=""
                        width="150"
                        className="inline-block"
                    />
                    <img
                        loading="lazy"
                        src="/logos/logo2.webp"
                        alt=""
                        width="150"
                        className="inline-block"
                    />
                    <img
                        loading="lazy"
                        src="/logos/logo3.webp"
                        alt=""
                        width="150"
                        className="inline-block"
                    />
                    <img
                        loading="lazy"
                        src="/logos/logo4.webp"
                        alt=""
                        width="150"
                        className="inline-block"
                    />
                    <img
                        loading="lazy"
                        src="/logos/logo5.webp"
                        alt=""
                        width="150"
                        className="inline-block"
                    />
                    <img
                        loading="lazy"
                        src="/logos/logo6.webp"
                        alt=""
                        width="150"
                        className="inline-block"
                    />
                </div>
            </div>
        </div>
    );
}

export default Carrusel;
